Error page404
Anzhelika007/e-commerce pull request #12
Opened 2024-05-11 10:16 UTC by cheidru

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Documentation

Task links: (https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint2/RSS-ECOMM-2_20.md)

Trello links: (https://trello.com/c/jlDvy0ry/47-rss-ecomm-220-implement-a-404-not-found-page-for-invalid-route-requests)

## Changes Made

List out the major changes in bullet points:

- Added a picture and information about the page is not found as well as the button to navigate to the main page.

## To do list:

- [ ] I've added information to the documentation.
- [x] I checked that my changes will not break the project.
- [ ] I added/updated test to check

## Checklist:

- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I added tests that prove my fix is effective or that my feature works.

2024-05-11 11:42 UTC, CerBeer approved these changes
Well done!

2024-05-12 11:09 UTC, Anzhelika007 requested changes
I don’t understand why this was not done on a working layout that contains layout according to the layout. If you explain it to me, I will continue to look at the code and conduct reviews

2024-05-13 15:09 UTC, Anzhelika007 approved these changes

2024-05-13 15:10 UTC, Anzhelika007 reviewed
God job!

2024-05-13 16:35 UTC, merged