Fixed task for mentor's comments
Anzhelika007/e-commerce pull request #7
Opened 2024-05-04 20:09 UTC by Anzhelika007

## Description
This pull request addresses several improvements and bug fixes across the project. The main changes include updating the HTML title, removing unused images, components, and styles, fixing Prettier script issues, cleaning up the Husky hook, and enhancing the test suite and ESLint configuration.

**Related Issue:** N/A

## Changes Made

### HTML Title Update
- Updated the `<title>` tag in the HTML to better reflect the current page content.

### Cleanup of Assets
- Removed unused images, extraneous components, and styles that were not being used, reducing the project's clutter and load time.

### Prettier Configuration Fix
- Modified the Prettier script to correctly locate files with specific extensions and include files directly under the `src` directory.

### Husky Hook Cleanup
- Removed the commented `#exit 1` from the Husky pre-commit hook script. This was a test command and is no longer needed.

### Test Suite Enhancement
- In `App.test.tsx`, updated the second test to check if certain text is rendered on the page, ensuring the app renders correctly.

### ESLint Configuration Improvement
- Suggested adding ESLint plugins for better code quality:
  - `plugin:jsx-a11y/recommended`
  - `plugin:react/jsx-runtime`
  - `plugin:react-hooks/recommended`

## How to Test
1. Check the HTML file to ensure the title has been updated correctly.
2. Verify that the removal of unused assets has not affected the functionality of the project.
3. Run the Prettier script to ensure no errors occur and it correctly formats files in the `src` directory.
4. Commit changes to test if the Husky pre-commit hook functions without the `#exit 1`.
5. Run tests in `App.test.tsx` to confirm the rendering checks are effective.
6. Review ESLint output to ensure no issues are reported with the new configuration and plugins.

## Checklist:
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in complex areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Additional Notes
Please familiarize yourself with the changes, especially the new ESLint plugins, to ensure ongoing compliance with the updated coding standards.

2024-05-05 08:12 UTC, fedorenksei requested changes
Кажется, скрипт для prettier не изменился

2024-05-05 08:12 UTC, fedorenksei commented on e-commerce/src/App.tsx
> +    <StrictMode>
Зачем здесь добавлен StrictMode, если в него уже все обернуто в main.tsx?

2024-05-05 08:12 UTC, fedorenksei commented on e-commerce/src/__tests__/App.test.tsx
> +    expect(true).toBeTruthy();
Эта строчка уже не нужна

2024-05-05 08:12 UTC, fedorenksei commented on e-commerce/src/__tests__/App.test.tsx
> +    expect(screen.getByText('ASInc store')).toBeInTheDocument();
Если использовать `getBy...`, то можно не оборачивать в `expect(...).toBeInTheDocument`, потому что `getBy...` само по себе выбросит ошибку, если элемент не найден. Сравните с `queryBy...` и `findBy...` https://testing-library.com/docs/queries/about/#types-of-queries

2024-05-05 08:12 UTC, fedorenksei commented on README.md
>  └── package-lock.json
Это кажется излишним, потому что потом еще и поддерживать, а ведь посмотреть структуру файлов можно и без README

2024-05-05 08:20 UTC, fedorenksei commented
На будущее, `fix` — плохое название для ветки, не описывает, что за фикс. И "for mentor's comments" — тоже не содержательное описание, потому что это только я знаю, о чем были comments :)

2024-05-05 15:20 UTC, Anzhelika007 commented on e-commerce/src/App.tsx
> +    <StrictMode>
Пофиксили

2024-05-05 15:20 UTC, Anzhelika007 commented on e-commerce/src/__tests__/App.test.tsx
> +    expect(true).toBeTruthy();
Убрали

2024-05-05 15:20 UTC, Anzhelika007 commented on e-commerce/src/__tests__/App.test.tsx
> +    expect(screen.getByText('ASInc store')).toBeInTheDocument();
Спасибо за статью - прочли, поняли

2024-05-05 15:21 UTC, Anzhelika007 commented on README.md
>  └── package-lock.json
Убрали

2024-05-06 16:15 UTC, cheidru approved these changes
I agree with these fixes

2024-05-06 16:16 UTC, CerBeer approved these changes
All proposals have been taken into account and implemented.
It's fine!

2024-05-06 16:16 UTC, merged